hello-world:
  handler: src/handlers/hello-world/get.handler
  events:
    - http:
        path: /hello-world
        method: get
        cors: true
        documentation:
          summary: get hello-world
  package:
    include:
        - ./resources/**
