make-pdf:
  handler: src/handlers/make-pdf/post.handler
  events:
    - http:
        path: /make-pdf
        method: post
        cors: true
        documentation:
          summary: create a pdf document
          requestModels:
              application/json: PostMakePdfRequest
  package:
    include:
        - ./resources/**
