API_VERSION: "v1"
CUSTOM_DOMAIN_CERTIFICATE_NAME: "*.sbx.zavasrv.com"
CUSTOM_DOMAIN_NAME: "make-pdf-service.sbx.zavasrv.com"
DYNAMOOSE_CREATE_TABLES: true
DYNAMOOSE_UPDATE_TABLES: true
RESOURCE_PREFIX: self:provider.region}:${self:custom.accountId}
STAGE_NAME: ${self:provider.stage}
TABLE_HELLO_WORLD:  "${self:service}-hello-world-${self:provider.stage}"
