Resources:
  RequestBodyValidation:
        Type: "AWS::ApiGateway::RequestValidator"
        Properties:
          Name: 'request-body-validator'
          RestApiId:
            Ref: ApiGatewayRestApi
          ValidateRequestBody: true
          ValidateRequestParameters: true